import { Sku } from "../../../types";

export const productsArr: Sku[] = [
  {
    info: "средство для мытья посуды Crystal",
    measureUnits: "ml",
    unitsCount: 450,
    art: "4604049097548",
    manufacturer: "Нэфис",
    brand: "AOS",
    images: [
      "https://s3-alpha-sig.figma.com/img/bb80/1e6a/432e70783222acc943e3f7db90754e36?Expires=1682899200&Signature=a703ZE8bSxKDCD3XHMIjCZodAZrMix~1vRoViThh7XdEIbE0rdjScdFeyfPjVifBC5RkB1bc18M3RnNQnBDOGq6eZwO7ii8MgIfPRzJsOCx4W4EO9jmXox~GnZz9ZKBxi8jQ2geJZWjAtzZPaE3uxTny8kbcGNyuEPG3lWqnPUJYQUh1MzpnNiVdzUaK~7kgQh8mM1Ph~1FVYxHADftOIrNCafMw~5QsquraEoZqHhG2hXvUT9KJDiUjlFXp946PHTMQk52w6Vv9ampVCprOXl517RyYYrOjs~TEazYrUztDPCyJULfM2fPBNit0ClMg7Q4r~qG2vqQtkrl4qxieXQ__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4",
    ],
    price: 48.76,
    pack: 0,
    categories: ["средство для мытья посуды"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repellendus recusandae minima quis, pariatur laboriosam sunt, odio ipsum, labore error amet magni deleniti temporibus quaerat?",
  },
  {
    info: "Экологичное туалетное мыло",
    measureUnits: "g",
    unitsCount: 90,
    art: "460404909754897",
    manufacturer: "BioMio",
    brand: "BIO-SOAP",
    images: [
      "https://s3-alpha-sig.figma.com/img/820a/961d/67c0ca0b8a6e475460317236d0091940?Expires=1682899200&Signature=m0rEwSC3jO1FHJQd-RlfJ~MyH3HfpnURHUIokO60NUIWLH04WwAFu4Y0k-pOhE4FZnfkWDR-h9I9PUrt-UplyORMhW3BSTQWDP5dJm6mQPywMIn5DUdbluKn~83JRtV~BfW0xCM3RAGV2OYe0WSphlhO-f-1EV9BrdSs-LS2XCTQGc78YQcmw3ccOAacymqj4KVKl28~xgixaXoX0m02zKOkX-BQTS3gXvCpqJGq-kR4wZwlwO1o8XRpwGDBY33urwQSkv77MSUi~2~qgQFBz~ClbAxe~cEF2VkvkU9K1UOQOebdkLN~tkkC-1l2KGZi8tNy7C7hfxgVIsSAW3VTRQ__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4",
    ],
    price: 20.5,
    pack: 0,
    categories: ["средство для мытья посуды", "туалетное мыло"],
    description:
      "Dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. ",
  },
  {
    info: "Порошок стиральный Автомат 100 пятен COMPACT",
    measureUnits: "g",
    unitsCount: 1500,
    art: "46040490975485",
    manufacturer: "J&J",
    brand: "BIMAX",
    images: [
      "https://s3-alpha-sig.figma.com/img/0018/dd96/8e6227c3d08e0a81121cd9a1891ab40b?Expires=1682899200&Signature=b3zA~EQfmX8ftx3eZD2ktcc5lTtVmXCiCN88-MBHYCrOGczbRaWV-Qa4azqiYEsT9vX7FvNZIzZMLxmuIrHwprE2QOvuZ4e2qLm3IFIsN8Hu96Q3jctCt9t2vBPlLUQRoqhRg8bZhwfXwEIHArRmBh09Nq9pVIg9ALqTq4FxGNRENdlNeCxCpwul98dsDYEBDp0ZkceClbUKu-gWHKKkY7ZZiSmE0Hj16SFxcJfelu7gGy9yxgYSl89O~-z5iblnu0RGa2jxwisnERVNt0KBfNDPhI8MfeV9tNZvdqchNtnwPjF7eR53ZbycUX5fINEH2uPIQhyv2X~Gv-uD9Nw8Sw__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4",
    ],
    price: 248.76,
    pack: 0,
    categories: ["средство для стирки"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repellendus recusandae minima quis, pariatur laboriosam sunt, odio ipsum, labore error amet magni deleniti temporibus quaerat?",
  },
  {
    info: " Автoмат Гель СМС жидкое в растворимых капсулах",
    measureUnits: "ml",
    unitsCount: 30,
    art: "4604049097548495",
    manufacturer: "J&J",
    brand: "ARIEL",
    images: [
      "https://s3-alpha-sig.figma.com/img/cb24/755e/02e4f5c045af34311b555cfc8eeeab8b?Expires=1682899200&Signature=WL1F2m6W11HfeVrNaXdDuORiYbb5kyJ21TiksOvcsGaqxvnOYnacugRcUNUIw8SYWWsj1euWIAXLNY8UoLfu3ndGF1Uye3kG07bLrlZcD59CPxqDKpTTX6hj6vJI9oCw6wkPfkuMP4GYjJas9LWldFJFv7L9vXkYIJYWtYbKZqApHBX0FimSEIv2nNKq8WguC9TgnKloScyWnU8iz7YQ~7Al4WOniXisaWGWWbA5rrP~OYEprdk54jbjA4h7-~IlikMbCfexDpWfHvj~uPgpXqjGhKWcoWGOippvJ8U03aM-BljCydthaAqrq216h3h85h0nS8q21K7peXTmIEdwUw__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4",
    ],
    price: 90.76,
    pack: 15,
    categories: ["средство для стирки"],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur repellendus recusandae minima quis, pariatur laboriosam sunt, odio ipsum, labore error amet magni deleniti temporibus quaerat?",
  },
  {
    measureUnits: "ml",
    unitsCount: 150,
    info: "Hyaluron Expert Replumping",
    art: "46040490973958",
    manufacturer: "L'Oreal Paris",
    pack: 0,
    brand: "L'Oreal Paris",
    images: [
      "https://i.dummyjson.com/data/products/16/1.png",
      "https://i.dummyjson.com/data/products/16/2.webp",
      "https://i.dummyjson.com/data/products/16/3.jpg",
      "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    ],
    price: 19,
    categories: ["средство для лица", "skincare"],
    description:
      "L'Oreal© Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
  },
  {
    measureUnits: "ml",
    unitsCount: 150,
    info: "Revitalift Derm Intensives",
    art: "46040490973526",
    manufacturer: "L'Oreal Paris",
    pack: 0,
    brand: "L'Oreal Paris",
    images: [
      "https://i.dummyjson.com/data/products/16/4.jpg",
      "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    ],
    price: 19,
    categories: ["средство для лица", "skincare"],
    description:
      "L'Oreal© Paris Revitalift Derm Intensives formulated with 1.5% Hyaluronic Acid",
  },
  {
    measureUnits: "ml",
    unitsCount: 450,
    manufacturer: "Hemani Tea",
    pack: 0,
    info: "Hyaluronic Acid Serum",
    brand: "Hemani Tea",
    categories: ["средство для лица", "skincare"],
    description:
      "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria",
    art: "174604049097548",
    images: [
      "https://i.dummyjson.com/data/products/17/1.jpg",
      "https://i.dummyjson.com/data/products/17/2.jpg",
      "https://i.dummyjson.com/data/products/17/3.jpg",
      "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    ],
    price: 12,
    stock: 78,
  },
  {
    measureUnits: "ml",
    unitsCount: 30,
    manufacturer: "Dermive",
    pack: 0,
    info: "Tree Oil Free Moisturizer",
    brand: "Dermive",
    categories: ["skincare"],
    description:
      "Dermive Oil Free Moisturizer with SPF 20 is ,specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    art: "184604049097548",
    images: [
      "https://i.dummyjson.com/data/products/18/1.jpg",
      "https://i.dummyjson.com/data/products/18/2.jpg",
      "https://i.dummyjson.com/data/products/18/3.jpg",
      "https://i.dummyjson.com/data/products/18/4.jpg",
      "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    ],
    price: 40,
    stock: 88,
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "ROREC",
    pack: 0,
    info: "Oil Free Moisturizer",
    brand: "ROREC White Rice",
    categories: ["skincare"],
    description:
      "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
    art: "194604049097548",
    images: [
      "https://i.dummyjson.com/data/products/19/1.jpg",
      "https://i.dummyjson.com/data/products/19/2.jpg",
      "https://i.dummyjson.com/data/products/19/3.png",
      "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    ],
    price: 46,
    stock: 54,
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Pakistan",
    pack: 0,
    brand: "Fair & Clear",
    categories: ["skincare"],
    description:
      "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
    art: "204604049097548",
    images: [
      "https://i.dummyjson.com/data/products/20/1.jpg",
      "https://i.dummyjson.com/data/products/20/2.jpg",
      "https://i.dummyjson.com/data/products/20/3.jpg",
      "https://i.dummyjson.com/data/products/20/4.jpg",
      "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    ],
    price: 70,
    stock: 140,
    info: "Freckle Treatment Cream- ",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "L'Oreal Paris",
    pack: 0,
    brand: "Impression of Acqua Di Gio",
    categories: ["fragrances"],
    description:
      "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",

    art: "114604909754897",
    images: [
      "https://i.dummyjson.com/data/products/11/1.jpg",
      "https://i.dummyjson.com/data/products/11/2.jpg",
      "https://i.dummyjson.com/data/products/11/3.jpg",
      "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    ],
    price: 13,
    stock: 65,
    info: "perfume Oil",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Royal",
    pack: 0,
    brand: "Royal Mirage",
    categories: ["fragrances"],
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    art: "8362440212",
    images: [
      "https://i.dummyjson.com/data/products/12/2.jpg",
      "https://i.dummyjson.com/data/products/12/3.png",
      "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    ],
    price: 40,
    stock: 52,
    info: "Brown Perfume",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Royal",
    pack: 0,
    brand: "Royal Mirage",
    categories: ["fragrances"],
    description: "Royal_Mirage Sport Silver Perfume for Men & Women - 120ml",
    art: "836244021293847",
    images: [
      "https://i.dummyjson.com/data/products/12/3.png",
      "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    ],
    price: 40,
    stock: 52,
    info: "Silver Perfume",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Fogg",
    pack: 0,
    brand: "Fog Scent Xpressio",
    categories: ["fragrances"],
    description:
      "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    art: "8362440213",
    images: [
      "https://i.dummyjson.com/data/products/13/1.jpg",
      "https://i.dummyjson.com/data/products/13/2.png",
      "https://i.dummyjson.com/data/products/13/3.jpg",
      "https://i.dummyjson.com/data/products/13/4.jpg",
      "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    ],
    price: 13,
    stock: 61,
    thumbnail: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    info: "Fog Scent Xpressio Perfume",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Mahal Al Musk",
    pack: 0,
    brand: "Al Munakh",
    categories: ["fragrances"],
    description:
      "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
    art: "8362440214",
    images: [
      "https://i.dummyjson.com/data/products/14/1.jpg",
      "https://i.dummyjson.com/data/products/14/2.jpg",
      "https://i.dummyjson.com/data/products/14/3.jpg",
      "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    ],
    price: 120,
    stock: 114,
    thumbnail: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    info: "Non-Alcoholic Concentrated Perfume Oil",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Al-Rehab",
    pack: 0,
    brand: "Lord - Al-Rehab",
    categories: ["fragrances"],
    description:
      "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    art: "8362440215",
    images: [
      "https://i.dummyjson.com/data/products/15/1.jpg",
      "https://i.dummyjson.com/data/products/15/3.jpg",
      "https://i.dummyjson.com/data/products/15/4.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
    price: 30,
    stock: 105,
    info: "Eau De Perfume Spray",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Al-Dirham",
    pack: 0,
    brand: "Lord - Al-Dirham",
    categories: ["fragrances"],
    description:
      "Genuine  Al-Dirham spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    art: "83624402151",
    images: [
      "https://i.dummyjson.com/data/products/15/2.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
    price: 30,
    stock: 105,
    info: "Eau De Perfume Spray",
  },
  {
    measureUnits: "ml",
    unitsCount: 15,
    manufacturer: "Chanel",
    pack: 0,
    brand: "Chanel #5",
    categories: ["fragrances"],
    description: "Genuine Chanel spray perfume from France High Quality",
    art: "83624402153",
    images: [
      "https://i.dummyjson.com/data/products/15/4.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
    price: 30,
    stock: 105,
    info: "Eau De Perfume Spray",
  },
];
